### PR TITLE
>:(

### PR DESCRIPTION
**Pull request by Laande**

### CODE REVIEW

**Comment by Dippys** [comment]
code is inefficient, why are you using single comments? combine them to a comment block.

**Review by Dippys — CHANGES_REQUESTED** [review]
Group of comments have to be combined into 1 comment block.

**Comment by Dippys** [comment]
> > Group of comments have to be combined into 1 comment block.
> 
> #84

Irrelevant Commit Not even merged, fix up your code 

> No good @Dippys our SLoC calculator considers comment blocks as a single line regardless of length.

True but it looks neater when reading through.

**Comment by Laande** [comment]
idk how to fix sorry ^^"

**Comment by sirjonasxx** [comment]
@ArachisH fix tanji

**Review by sirjonasxx — APPROVED** [review]
good

**Pull request closed without merging**
