### PR TITLE
Fix for certificatePath which includes spaces

### PR DESCRIPTION
**Pull request by WiredSpast**
Encapsulated certificatePath in " "

### CODE REVIEW

**Comment by sirjonasxx** [comment]
looks good did u test it

**Comment by WiredSpast** [comment]
I tested the [shell command](https://github.com/sirjonasxx/G-Earth/blob/3d6e7d5b322bb67fac4e3e2933c13fc4aa68609d/G-Earth/src/main/java/gearth/protocol/connection/proxy/nitro/os/windows/NitroWindows.java#L44) in powershell
image

And the [regular command](https://github.com/sirjonasxx/G-Earth/blob/3d6e7d5b322bb67fac4e3e2933c13fc4aa68609d/G-Earth/src/main/java/gearth/protocol/connection/proxy/nitro/os/windows/NitroWindows.java#L28) in Command prompt
image

Haven't tested is compiled in G-Earth no

**Comment by WiredSpast** [comment]
Wait that second screen is the wrong screenshot

**Comment by WiredSpast** [comment]
This one is the one with a space in the path
image

**Review by sirjonasxx — APPROVED** [review]

**Comment by WiredSpast** [comment]
I just tried it compiled, the install works now, the check doesn't

**Pull request merged**
