### PR TITLE
Lets the OS decide extension server port

### PR DESCRIPTION
**Pull request by aromaa**
Using port 0 lets the OS to figure out which port is free and bind to it. Then we can just check which port we bound to.

### CODE REVIEW

**Comment by heliocosta1337** [comment]
Elegant

**Comment by sirjonasxx** [comment]
The reason I didn't do this is so there is a default port for extensions to use when developing, you probably wouldn't want to reconfigure this in your IDE every time you open G-earth. Now you can just set a default to 9092 and assume it will work if you only have 1 G-Earth instance open (while testing)

**Comment by aromaa** [comment]
Hmm. Right. We could first bind to 9092 and if that fails then just fallback to using random one.

**Comment by dosier** [comment]
I prefer to keep the sequential port range, which makes it easier to know what port each instance is bound to when running multiple instances. But you could improve upon the open port checking code, that always seemed kinda sus to me.

**Comment by Alynva** [comment]
> Hmm. Right. We could first bind to 9092 and if that fails then just fallback to using random one.

What's the point of having a random port every time? Hide that you're using G-Earth?

**Comment by Julianty123** [comment]
@Alynva I think it means that if a port is selected programmatically, there is a risk that it is busy

**Comment by Alynva** [comment]
> @Alynva I think it means that if a port is selected programmatically, there is a risk that it is busy

```java
        port = PORT_ONSET; 
         while (!available(port)) 
             port++;
```

**Comment by dorving** [comment]
I vote for keeping the incremental port as the default behavior. One thing I would not be opposed to is to allow for an optional environment variable to be set that specifies the port onset, if not specified, the onset will remain `9092`.

**Pull request closed without merging**
