### PR TITLE
Allow onClick method to be overridden in console extensions

### PR DESCRIPTION
**Pull request by WiredSpast**
The `onClick` method had a package-private access modifier in the `ExtensionBase` class, I changed it to protected.

I also made the `onClick` in `ExtensionForm` final, this way it can't be overridden in GUI extensions.

### CODE REVIEW

**Comment by Julianty123** [comment]
Seriously, why are you ban me? Have you discord to talk?

**Comment by sirjonasxx** [comment]
is this ready for merge? since there's some unity stuff

**Comment by JonasssC** [comment]
Oops the unity stuff shouldn't have been added to the pr

**Comment by WiredSpast** [comment]
I've removed the unity stuff, should be fine now

**Review by sirjonasxx — APPROVED** [review]

**Pull request merged**
